# Installation helper
#
# ensure we have build tools and c compiler installed
# on ubuntu we can run `sudo apt install build-essential`
#
# Erlang and Elixir
# refer to https://www.erlang.org/doc/system/install.html
# to install `ncurses` on ubuntu run `sudo apt install libncurses5-dev libncursesw5-dev`
#
# Ruby
# to install required library on ubunt run `sudo apt install libz-dev libssl-dev libffi-dev libyaml-dev`
#

[tools]
bun = "latest"
deno = "latest"
ruby = "latest"
cocoapods = "latest"
elixir = "latest"
erlang = "latest"
go = "latest"
java = "latest"
node = "24"
python = "3.12"
rust = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
